// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: enhancement.proto

package enhancement

import (
	common "go/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnhanceItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *common.Item           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnhanceItemRequest) Reset() {
	*x = EnhanceItemRequest{}
	mi := &file_enhancement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnhanceItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnhanceItemRequest) ProtoMessage() {}

func (x *EnhanceItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enhancement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnhanceItemRequest.ProtoReflect.Descriptor instead.
func (*EnhanceItemRequest) Descriptor() ([]byte, []int) {
	return file_enhancement_proto_rawDescGZIP(), []int{0}
}

func (x *EnhanceItemRequest) GetItem() *common.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type EnhanceItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *common.Item           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnhanceItemResponse) Reset() {
	*x = EnhanceItemResponse{}
	mi := &file_enhancement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnhanceItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnhanceItemResponse) ProtoMessage() {}

func (x *EnhanceItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enhancement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnhanceItemResponse.ProtoReflect.Descriptor instead.
func (*EnhanceItemResponse) Descriptor() ([]byte, []int) {
	return file_enhancement_proto_rawDescGZIP(), []int{1}
}

func (x *EnhanceItemResponse) GetItem() *common.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_enhancement_proto protoreflect.FileDescriptor

var file_enhancement_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x1a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x12, 0x45, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x37, 0x0a, 0x13,
	0x45, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x04, 0x69, 0x74, 0x65, 0x6d, 0x32, 0x66, 0x0a, 0x12, 0x45, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0b, 0x45,
	0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1f, 0x2e, 0x65, 0x6e, 0x68,
	0x61, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x65, 0x6e,
	0x68, 0x61, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x68, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x22, 0x5a,
	0x20, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x3b, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_enhancement_proto_rawDescOnce sync.Once
	file_enhancement_proto_rawDescData []byte
)

func file_enhancement_proto_rawDescGZIP() []byte {
	file_enhancement_proto_rawDescOnce.Do(func() {
		file_enhancement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enhancement_proto_rawDesc), len(file_enhancement_proto_rawDesc)))
	})
	return file_enhancement_proto_rawDescData
}

var file_enhancement_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_enhancement_proto_goTypes = []any{
	(*EnhanceItemRequest)(nil),  // 0: enhancement.EnhanceItemRequest
	(*EnhanceItemResponse)(nil), // 1: enhancement.EnhanceItemResponse
	(*common.Item)(nil),         // 2: common.Item
}
var file_enhancement_proto_depIdxs = []int32{
	2, // 0: enhancement.EnhanceItemRequest.item:type_name -> common.Item
	2, // 1: enhancement.EnhanceItemResponse.item:type_name -> common.Item
	0, // 2: enhancement.EnhancementService.EnhanceItem:input_type -> enhancement.EnhanceItemRequest
	1, // 3: enhancement.EnhancementService.EnhanceItem:output_type -> enhancement.EnhanceItemResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_enhancement_proto_init() }
func file_enhancement_proto_init() {
	if File_enhancement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enhancement_proto_rawDesc), len(file_enhancement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enhancement_proto_goTypes,
		DependencyIndexes: file_enhancement_proto_depIdxs,
		MessageInfos:      file_enhancement_proto_msgTypes,
	}.Build()
	File_enhancement_proto = out.File
	file_enhancement_proto_goTypes = nil
	file_enhancement_proto_depIdxs = nil
}
